foo.js:4
  4: p = 'bar';
         ^^^^^ string. This type is incompatible with
  3: var p : number = 0;
             ^^^^^^ number

foo.js:7
  7: n = 'foo';
         ^^^^^ string. This type is incompatible with
  6: var {n} : {n : number} = {n : 3};
          ^ number

foo.js:10
 10: i = 'lol';
         ^^^^^ string. This type is incompatible with
  9: var [i] : [number] = [0];
          ^ number


Found 3 errors
